### ISSUE TITLE
QUESTION: Is there a supported ES version that's not affected by log4shell?

### ISSUE THREAD

**Issue by j3j5** [10up/ElasticPress#2540]
Looking at the README I understand that the latest supported version of Elastic is 7.9, but, as far as I can see, the latest 7.9.x version is 7.9.3 which is affected by the Log4Shell vulnerabilities (CVE-2021-44228, CVE-2021-45046 and CVE-2021-45105). Am I missing something or does this extension not support any of the safe Elasticsearch versions on the 7.x branch?

**Comment by mckdemps** [comment]
Elastic often introduces breaking changes in new versions, so ElasticPress compatibility is usually a few minor versions behind. However, you can help us prepare for newer versions by testing them and letting us know in this ticket if they are compatible with ElasticPress.

**Comment by fgbreel** [comment]
Hi, seem that elasticpress work _ok_ with elasticsearch `7.16.2` (I can at least index and search posts).

**Comment by Dave3o3** [comment]
add "-Dlog4j2.formatMsgNoLookups=true" to your ES_JAVA_OPTS

in docker-compose:

```yaml
#...
elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    restart: always
    environment:
     #...
      ES_JAVA_OPTS: "-Dlog4j2.formatMsgNoLookups=true"
#...
```
